version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    reviewers:
      - "buildkite/mobile-delivery-cloud"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    reviewers:
      - "buildkite/mobile-delivery-cloud"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
