name: flappykite
services:
  bazel-remote:
    container_name: bazel-remote-cache
    command:
      [
        "--max_size=15",
        "--experimental_remote_asset_api",
        "--profile_port=0",
        "--dir=.cache",
        "--enable_endpoint_metrics",
      ]
    restart: always
    image: buchgr/bazel-remote-cache:v2.3.3
    user: 0:0
    volumes:
      - ../.cache/bazel/remote:/data:rw
  app:
    image: gcr.io/bazel-public/bazel:7.4.1
    working_dir: /app
    volumes:
      - ../:/app
    depends_on:
      - bazel-remote
