agents:
  queue: macos-large

cache:
  paths:
    - "vendor/bundle"
    - "DerivedData"
  size: "20g"

steps:
  - label: ":ruby: install dependencies"
    key: install-dependencies-ruby
    command: .buildkite/scripts/install-dependencies.sh

  - label: ":macos: build"
    key: build-apple
    command: .buildkite/scripts/build.sh
    depends_on:
      - install-dependencies-ruby

  - label: ":macos: test"
    command: .buildkite/scripts/test.sh
    depends_on:
      - build-apple
    artifact_paths: 
      - "fastlane/test_output/report.junit"

  - label: ":macos: :camera: screenshots"
    command: .buildkite/scripts/screenshots.sh
    depends_on:
      - build-apple
    artifact_paths:
      - "screenshots/**/*.png"
