agents:
  queue: macos-large

steps:
  - label: ":ruby: install dependencies"
    key: install-dependencies-ruby
    command: .buildkite/scripts/install-dependencies.sh

  - label: ":macos: build"
    key: build-apple
    command: .buildkite/scripts/build.sh
    depends_on:
      - install-dependencies-ruby

  - label: ":macos: test"
    command: .buildkite/scripts/test.sh
    depends_on:
      - build-apple
    artifact_paths:
      - "fastlane/test_output/report.junit"

  - label: ":macos: :camera: screenshots"
    command: .buildkite/scripts/screenshots.sh
    depends_on:
      - build-apple
    artifact_paths:
      - "screenshots/**/*.png"

  - label: ":bazel: build"
    key: bazel-build
    soft_fail: true
    cache:
      paths:
        - ".cache"
      size: "20g"
    plugins:
      - docker-compose#v5.3.0:
          run: app
          config: .buildkite/docker-compose.yml
          shell: false
          command: ["build", "--config=buildkite", "--", "//..."]
    agents:
      queue: hosted_linux_small

  - label: ":bazel: test"
    key: bazel-test
    depends_on:
      - bazel-build
    soft_fail: true
    cache:
      paths:
        - ".cache"
      size: "20g"
    plugins:
      - docker-compose#v5.3.0:
          run: app
          config: .buildkite/docker-compose.yml
          shell: false
          command: ["test", "--config=buildkite", "--", "//..."]
    agents:
      queue: hosted_linux_small
