agents:
  queue: macos-large

steps:
  - label: ":ruby: install dependencies"
    key: install-dependencies-ruby
    command: .buildkite/scripts/install-dependencies.sh

  - label: ":macos: build"
    key: build-apple
    command: .buildkite/scripts/build.sh
    depends_on:
      - install-dependencies-ruby

  - label: ":macos: test"
    command: .buildkite/scripts/test.sh
    depends_on:
      - build-apple
    artifact_paths:
      - "fastlane/test_output/report.junit"

  - label: ":macos: :camera: screenshots"
    command: .buildkite/scripts/screenshots.sh
    depends_on:
      - build-apple
    artifact_paths:
      - "screenshots/**/*.png"

  - label: ":bazel: build"
    key: bazel-build
    command: "bazelisk --bazelrc=.bazelrc --bazelrc=.bazelrc-generated build --config=buildkite //FlappyKite:FlappyKite"
    env:
      AWS_REGION: us-east-1
    cache:
      paths:
        - ".cache"
      size: "20g"
      name: "bazel"
    plugins:
      - aws-assume-role-with-web-identity#v1.1.0:
          role-arn: "arn:aws:iam::724772075326:role/oidc-flappykite-secretsmanager"
      - aws-secretsmanager-to-bazelrc#main:
          bazel-config: "buildkite"
          output-filename: ".bazelrc-generated"
          path: "pipelines/flappykite/bazel"

  - label: ":bazel: test"
    key: bazel-test
    depends_on:
      - bazel-build
    command: "bazelisk --bazelrc=.bazelrc --bazelrc=.bazelrc-generated test --config=buildkite //FlappyKiteTests:FlappyKiteTests //FlappyKiteUITests:FlappyKiteUITests"
    env:
      AWS_REGION: us-east-1
    cache:
      paths:
        - ".cache"
      size: "20g"
      name: "bazel"
    plugins:
      - aws-assume-role-with-web-identity#v1.1.0:
          role-arn: "arn:aws:iam::724772075326:role/oidc-flappykite-secretsmanager"
      - aws-secretsmanager-to-bazelrc#main:
          bazel-config: "buildkite"
          output-filename: ".bazelrc-generated"
          path: "pipelines/flappykite/bazel"
