agents:
  queue: macos-large

steps:
  - label: ":ruby: install dependencies"
    key: install-dependencies-ruby
    command: .buildkite/scripts/install-dependencies.sh
  - label: ":macos: build"
    key: build-apple
    command: .buildkite/scripts/build.sh
    depends_on: [install-dependencies-ruby]
  - label: ":macos: test"
    command: .buildkite/scripts/test.sh
    depends_on: [build-apple]
    artifact_paths: 
      - "fastlane/test_output/report.junit"
